#version: '42'
services:
  quarantine:
    build: .
    volumes:
      - ./infection:/root/infection
    secrets:
      - source: stockholm
        target: stockholm
        mode: 0511
secrets:
  stockholm:
    file: ./stockholm
